spring:
  application:
    name: diff-api
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
  datasource:
    url: jdbc:mysql://db:3306/diff-api?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password

server:
  port: 9000

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl:
    auto: validate
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    name: "./logs/diff-api.log"